-- =========================================================
-- Database schema for the news-topics-ner project
-- =========================================================

-- CREATE SCHEMA news_nlp;

-- =========================================================
-- 1. News table
-- =========================================================

CREATE TABLE IF NOT EXISTS news (
    news_id       BIGSERIAL PRIMARY KEY,
    external_id   VARCHAR(255),                  -- original id from source, if any
    source        VARCHAR(50) NOT NULL DEFAULT 'train',  -- 'train','test','prod',...
    title         TEXT NOT NULL,
    content       TEXT NOT NULL,
    text_clean    TEXT,                          -- preprocessed version of the text
    ingested_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_news_source
    ON news(source);


-- =========================================================
-- 2. Topic model runs (each training of the topic model)
-- =========================================================

CREATE TABLE IF NOT EXISTS topic_runs (
    topic_run_id       BIGSERIAL PRIMARY KEY,
    mlflow_run_id      VARCHAR(64) UNIQUE,       -- link to MLflow run (optional but nice to have)
    model_name         VARCHAR(100) NOT NULL DEFAULT 'tfidf_svd_kmeans',
    n_components       INT NOT NULL,             -- number of SVD components
    n_clusters         INT NOT NULL,             -- k in K-Means
    tfidf_max_features INT,
    tfidf_min_df       DOUBLE PRECISION,
    tfidf_max_df       DOUBLE PRECISION,
    random_state       INT,
    silhouette         DOUBLE PRECISION,
    created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_active          BOOLEAN NOT NULL DEFAULT FALSE
);

-- Ensure there can be at most *one* active topic_run at a time
CREATE UNIQUE INDEX IF NOT EXISTS uq_topic_runs_active
    ON topic_runs(is_active)
    WHERE is_active = TRUE;


-- =========================================================
-- 3. Topics table (one row per topic/cluster and run)
-- =========================================================

CREATE TABLE IF NOT EXISTS topics (
    topic_run_id  BIGINT NOT NULL
        REFERENCES topic_runs(topic_run_id) ON DELETE CASCADE,
    topic_id      INT    NOT NULL,              -- cluster id (0..k-1)
    name          VARCHAR(255) NOT NULL,        -- short label (generated by LLM)
    description   TEXT,                         -- optional longer description
    size          INT,                          -- number of training news assigned to this topic
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (topic_run_id, topic_id)
);

CREATE INDEX IF NOT EXISTS idx_topics_run
    ON topics(topic_run_id);


-- =========================================================
-- 4. Topic terms (top representative terms per topic)
-- =========================================================

CREATE TABLE IF NOT EXISTS topic_terms (
    topic_run_id  BIGINT NOT NULL,
    topic_id      INT    NOT NULL,
    rank          INT    NOT NULL,              -- 1 = most representative term for this topic
    term          TEXT   NOT NULL,
    weight        DOUBLE PRECISION,             -- e.g. average tf-idf weight within this topic
    PRIMARY KEY (topic_run_id, topic_id, rank),
    FOREIGN KEY (topic_run_id, topic_id)
        REFERENCES topics(topic_run_id, topic_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_topic_terms_term
    ON topic_terms(term);


-- =========================================================
-- 5. News–topic assignments (one row per news and topic_run)
-- =========================================================

CREATE TABLE IF NOT EXISTS news_topics (
    news_id              BIGINT NOT NULL
        REFERENCES news(news_id) ON DELETE CASCADE,
    topic_run_id         BIGINT NOT NULL
        REFERENCES topic_runs(topic_run_id) ON DELETE CASCADE,
    topic_id             INT    NOT NULL,
    distance_to_centroid DOUBLE PRECISION,      -- distance in the reduced feature space
    assigned_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (news_id, topic_run_id),
    FOREIGN KEY (topic_run_id, topic_id)
        REFERENCES topics(topic_run_id, topic_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_news_topics_topic
    ON news_topics(topic_run_id, topic_id);

CREATE INDEX IF NOT EXISTS idx_news_topics_news
    ON news_topics(news_id);


-- =========================================================
-- 6. Entities dictionary (unique entities across all news)
-- =========================================================

CREATE TABLE IF NOT EXISTS entities (
    entity_id      BIGSERIAL PRIMARY KEY,
    entity_text    TEXT NOT NULL,
    entity_norm    TEXT NOT NULL,               -- normalized form ('joe biden')
    entity_label   VARCHAR(50) NOT NULL,        -- PERSON, ORG, GPE, LOC, ...
    mention_count  INT,                         -- total number of mentions in the corpus
    news_count     INT,                         -- number of distinct news where it appears
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Ensure (entity_norm, entity_label) is unique so we can safely upsert
CREATE UNIQUE INDEX IF NOT EXISTS uq_entities_norm_label
    ON entities(entity_norm, entity_label);

CREATE INDEX IF NOT EXISTS idx_entities_label
    ON entities(entity_label);

CREATE INDEX IF NOT EXISTS idx_entities_norm
    ON entities(entity_norm);


-- =========================================================
-- 7. News–entity relations (which entities appear in which news)
-- =========================================================

CREATE TABLE IF NOT EXISTS news_entities (
    news_id       BIGINT NOT NULL
        REFERENCES news(news_id) ON DELETE CASCADE,
    entity_id     BIGINT NOT NULL
        REFERENCES entities(entity_id) ON DELETE CASCADE,
    mention_count INT    NOT NULL,              -- mentions of this entity in this news article
    PRIMARY KEY (news_id, entity_id)
);

CREATE INDEX IF NOT EXISTS idx_news_entities_entity
    ON news_entities(entity_id);

CREATE INDEX IF NOT EXISTS idx_news_entities_news
    ON news_entities(news_id);
