-- =========================================================
-- SCHEMA FOR news_nlp PROJECT
-- =========================================================

-- ======================
-- 1) Table: news
-- ======================
CREATE TABLE IF NOT EXISTS news (
    id_news      BIGSERIAL PRIMARY KEY,
    source       VARCHAR(50) NOT NULL,       -- 'train', 'test', 'prod', ...
    title        TEXT NOT NULL,
    content      TEXT NOT NULL,
    text         TEXT NOT NULL,              -- cleaned text used for modeling
    ingested_at  TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_news_source
    ON news(source);


-- ======================
-- 2) Table: topics_model_training_runs
-- Each row represents one training run of the topics detector
-- ======================
CREATE TABLE IF NOT EXISTS topics_model_training_runs (
    id_run              BIGSERIAL PRIMARY KEY,
    id_mlflow_run       VARCHAR(255),         -- optional, to link with MLflow later
    model_name          VARCHAR(100) NOT NULL DEFAULT 'tfidf_svd_kmeans',
    tfidf_max_features  INT,
    tfidf_max_df        FLOAT,
    tfidf_min_df        FLOAT,
    tfidf_ngram_range   TEXT,                 -- e.g. '(1, 2)'
    tfidf_stop_words    VARCHAR(50) NOT NULL DEFAULT 'english',
    svd_n_components    INT NOT NULL,         -- number of SVD components
    kmeans_n_clusters   INT NOT NULL,         -- k in K-Means
    kmeans_n_init       VARCHAR(20) NOT NULL DEFAULT 'auto', -- 'auto', '10', ...
    top_terms_per_topic INT,
    random_state        INT,
    silhouette          FLOAT,
    created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    is_active           BOOLEAN NOT NULL DEFAULT TRUE
);

-- Ensure there can be at most *one* active topic_run at a time
CREATE UNIQUE INDEX IF NOT EXISTS ux_topics_model_training_runs_is_active
    ON topics_model_training_runs (is_active)
    WHERE is_active = TRUE;


-- ======================
-- 3) Table: topics
-- Each row is a single topic (cluster) for a given run
-- ======================
CREATE TABLE IF NOT EXISTS topics (
    id_run      BIGINT NOT NULL
        REFERENCES topics_model_training_runs(id_run)
        ON DELETE CASCADE,
    id_topic    INT    NOT NULL,            -- 0 .. k-1 within a run
    topic_name  TEXT,                       -- short label for the topic generated by LLM
    topic_size  INT    NOT NULL,            -- number of news items assigned to this topic  
    created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id_run, id_topic)
);

CREATE INDEX IF NOT EXISTS idx_topics_id_run
    ON topics(id_run);


-- ======================
-- 4) Table: terms_per_topic
-- Top terms for each topic (cluster) in a given run
-- ======================
CREATE TABLE IF NOT EXISTS terms_per_topic (
    id_run  BIGINT NOT NULL
        REFERENCES topics_model_training_runs(id_run)
        ON DELETE CASCADE,
    id_topic INT   NOT NULL,
    rank     INT   NOT NULL,                 -- 1..N (order of importance)
    term     TEXT  NOT NULL,
    weight   FLOAT NOT NULL,                 -- e.g. mean tf-idf weight
    PRIMARY KEY (id_run, id_topic, rank),
    FOREIGN KEY (id_run, id_topic)
        REFERENCES topics(id_run, id_topic)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_terms_per_topic_id_run
    ON terms_per_topic(id_run);


-- ======================
-- 5) Table: topics_per_news
-- Assignment of each news item to a topic (cluster) for a given run
-- ======================
CREATE TABLE IF NOT EXISTS topics_per_news (
    id_news  BIGINT NOT NULL
        REFERENCES news(id_news)
        ON DELETE CASCADE,
    id_run   BIGINT NOT NULL
        REFERENCES topics_model_training_runs(id_run)
        ON DELETE CASCADE,
    id_topic INT    NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (id_news, id_run),
    FOREIGN KEY (id_run, id_topic)
        REFERENCES topics(id_run, id_topic)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_topics_per_news_id_run
    ON topics_per_news(id_run);


-- ======================
-- 6) Table: entities
-- Global table of unique named entities detected in the corpus
-- ======================
CREATE TABLE IF NOT EXISTS entities (
    id_entity              BIGSERIAL PRIMARY KEY,
    entity_text            TEXT NOT NULL,    -- representative text form
    entity_text_norm       TEXT,             -- normalized / canonical form
    entity_type            VARCHAR(50),      -- e.g. PERSON, ORG, GPE, LOC...
    entity_mentions_count  INT    NOT NULL DEFAULT 0,  -- total mentions in all news
    news_count             INT    NOT NULL DEFAULT 0,  -- number of distinct news where it appears
    created_at             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_entities_entity_text_norm
    ON entities(entity_text_norm);


-- ======================
-- 7) Table: entities_per_news
-- Mentions of entities in each news item
-- ======================
CREATE TABLE IF NOT EXISTS entities_per_news (
    id_news               BIGINT NOT NULL
        REFERENCES news(id_news)
        ON DELETE CASCADE,
    id_entity             BIGINT NOT NULL
        REFERENCES entities(id_entity)
        ON DELETE CASCADE,
    entity_mentions_count INT    NOT NULL,   -- number of mentions of this entity in this news
    PRIMARY KEY (id_news, id_entity)
);

CREATE INDEX IF NOT EXISTS idx_entities_per_news_id_entity
    ON entities_per_news(id_entity);
