from typing import Dict, List, Tuple

import numpy as np
import pandas as pd

from news_nlp.topics_detector.model import TopicModelConfig, TopicModelArtifacts


def build_topics_model_training_run_row(
    config: TopicModelConfig,
    artifacts: TopicModelArtifacts,
) -> pd.DataFrame:
    """
    Build a one-row dataframe to insert into topics_model_training_runs.

    Note: id_run and created_at are generated by the database.
    """
    data = {
        "id_mlflow_run": [None],  # to be linked with MLflow later
        "model_name": [config.model_name],
        "tfidf_max_features": [config.tfidf_max_features],
        "tfidf_max_df": [float(config.tfidf_max_df)],
        "tfidf_min_df": [float(config.tfidf_min_df)],
        "tfidf_ngram_range": [f"{config.tfidf_ngram_range[0]}-{config.tfidf_ngram_range[1]}"],
        "tfidf_stop_words": [config.tfidf_stop_words],     
        "svd_n_components": [config.svd_n_components],
        "kmeans_n_clusters": [config.kmeans_n_clusters],
        "kmeans_n_init": [str(config.kmeans_n_init)],
        "top_terms_per_topic": [config.top_terms_per_topic],
        "random_state": [config.random_state],
        "silhouette": [artifacts.silhouette],
        "is_active": [True],
    }
    return pd.DataFrame(data)


def build_topics_dataframe(
    id_run: int,
    cluster_labels: np.ndarray,
    topic_names: Dict[int, str],
) -> pd.DataFrame:
    """
    Build a dataframe for the topics table.

    Columns:
      - id_run
      - id_topic
      - topic_name
      - topic_size
    """
    unique_topics = sorted(set(cluster_labels.tolist()))
    rows = []

    for id_topic in unique_topics:
        mask = cluster_labels == id_topic
        topic_size = int(mask.sum())
        topic_name = topic_names.get(id_topic, f"Topic {id_topic}")

        rows.append(
            {
                "id_run": id_run,
                "id_topic": id_topic,
                "topic_name": topic_name,
                "topic_size": topic_size,
            }
        )

    return pd.DataFrame(rows)


def build_terms_per_topic_dataframe(
    id_run: int,
    top_terms_per_topic: Dict[int, List[Tuple[str, float]]],
) -> pd.DataFrame:
    """
    Build a dataframe for the terms_per_topic table.

    Columns:
      - id_run
      - id_topic
      - rank
      - term
      - weight
    """
    rows = []

    for id_topic, terms in top_terms_per_topic.items():
        for rank, (term, weight) in enumerate(terms, start=1):
            rows.append(
                {
                    "id_run": id_run,
                    "id_topic": id_topic,
                    "rank": rank,
                    "term": term,
                    "weight": float(weight),
                }
            )

    return pd.DataFrame(rows)


def build_topics_per_news_dataframe(
    id_run: int,
    news_ids: np.ndarray,
    cluster_labels: np.ndarray,
) -> pd.DataFrame:
    """
    Build a dataframe for the topics_per_news table.

    Columns:
      - id_news
      - id_run
      - id_topic
    """
    if len(news_ids) != len(cluster_labels):
        raise ValueError("news_ids and labels must have the same length.")

    rows = []
    for id_news, id_topic in zip(news_ids, cluster_labels):
        rows.append(
            {
                "id_news": int(id_news),
                "id_run": id_run,
                "id_topic": int(id_topic),
            }
        )

    return pd.DataFrame(rows)
